---
title: "class11"
author: "Xiao"
date: "2019/5/7"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## the PDB database

The [PDB](http://www.rcsb.org/) is the main repository for biomolecualr 
structral database

Here we examine the content sof the PDB

```{r}
db <- read.csv("Data Export Summary.csv")
head(db)
# How many are X-Ray
db$Total[1] / sum(db$Total)
# How many are proteins
sum(db$Proteins) / sum(db$Total)
```

```{r}
library(datapasta)
# Addins -> Paste as dataframe
tmp <- data.frame(stringsAsFactors=FALSE,
          Experimental.Method = c("X-Ray", "NMR", "Electron Microscopy", "Other",
                                  "Multi Method", "Total"),
                     Proteins = c(126880, 11062, 2277, 256, 129, 140604),
                Nucleic.Acids = c(2012, 1279, 31, 4, 5, 3331),
           ProteinComplex = c(6547, 259, 800, 6, 2, 7614),
                        Other = c(8, 8, 0, 13, 1, 30),
                        Total = c(135447, 12608, 3108, 279, 137, 151579)
       )

```

There are 1157 as of 2019-05-07 See:
http://www.rcsb.org/pdb/results/results.do?tabtoshow=Current&qrid=F0A699D4

```{r}
library(bio3d)
example(plot.bio3d)
```

```{r}
pdb <- read.pdb("1hsg")
pdb
attributes(pdb)
head(pdb$atom)
pdb$atom[1:2, c("eleno", "elety", "x","y","z")]
pdb$atom$elety[1:2]
plot.bio3d(pdb$atom$b[pdb$calpha], sse=pdb, typ="l", ylab="B-factor")
```

Atom selection is done via the function atom.select
```{r}
lig.pdb <- atom.select(pdb, "ligand", value = T)
write.pdb(lig.pdb, file = "1hsg_ligand.pdb")
```

```{r}
prot.pdb <- atom.select(pdb, "protein", value = T)
write.pdb(prot.pdb, file = "1hsg_protein.pdb")
```

```{r}

```

