---
title: "Class 09"
author: "Xiao"
date: "2019/4/30"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load in data
```{r}
wisc.df <- read.csv("WisconsinCancer.csv")
wisc.data <- as.matrix(wisc.df[, 3: 32])
```
```{r}
row.names(wisc.data) <- wisc.df$id
diagnosis <- as.numeric(wisc.df$diagnosis == "M") #Concert M to 1; B to 0
```
# Question 1-3
```{r}
nrow(wisc.df) #Q1
length(grep("_mean", colnames(wisc.data))) #Q2
table(wisc.df$diagnosis) #Q3
```

# check the data should be scaled
```{r}
round(colMeans(wisc.data)) 
round(apply(wisc.data,2,sd)) 
```

# Performing PCA
```{r}
wisc.pr <- prcomp(wisc.data, scale = T)
summary(wisc.pr)
```
```{r}
library(rgl)
plot3d(wisc.pr$x[,1:3], xlab="PC 1", ylab="PC 2", zlab="PC 3", cex=1.5, size=1, type="s", col=diagnosis+1)
```

```{r}
plot(wisc.pr$x[, 1], wisc.pr$x[, 2], col = diagnosis + 1)
```


# Question 4-6
```{r}
# Q4. From your results, what proportion of the original variance is captured by the first principal components (PC1)?
0.4427
# Q5. How many principal components (PCs) are required to describe at least 70% of the original variance in the data?
"PC3"
# Q6. How many principal components (PCs) are required to describe at least 90% of the original variance in the data?
"PC7"
```

# Intepreting PCA results
```{r}
pr.var <- wisc.pr$sdev^2
pve <- pr.var / sum(pr.var)
biplot(wisc.pr)
plot(wisc.pr$x[, c(1, 3)] , col = (diagnosis + 1), xlab = "PC1", ylab = "PC2")

barplot(pve, ylab = "Precent of Variance Explained",
     names.arg=paste0("PC",1:length(pve)), las=2, axes = FALSE)
axis(2, at=pve, labels=round(pve,2)*100 )

plot(pve, xlab = "Principal Component", 
     ylab = "Cumulative Proportion of Variance Explained", 
     ylim = c(0, 1), type = "o")
```

```{r}
plot(cumsum(pve), xlab = "Principal Component", 
     ylab = "Cumulative Proportion of Variance Explained", 
     ylim = c(0, 1), type = "o")
```

# Hiearchical clustering 
```{r}
data.scaled <- scale(wisc.data)
data.dist <- dist(data.scaled)
wisc.hclust <- hclust(data.dist, method = "complete")
plot(wisc.hclust)
wisc.hclust.clusters <- cutree(wisc.hclust, k = 4)
abline(h = 15, col = "red")
table(wisc.hclust.clusters, diagnosis)
```

# Combining the methods
```{r}
wisc.pr.hclust <- hclust(dist(wisc.pr$x[, 1: 7]), method = "ward.D2")
plot(wisc.pr.hclust)
grps <- cutree(wisc.pr.hclust, k=2)
table(grps)
```

```{r}
table(grps, diagnosis)
plot(wisc.pr$x[, 1], wisc.pr$x[, 2], col = grps)
```
# Prediction
```{r}
url <- "https://tinyurl.com/new-samples-CSV"
new <- read.csv(url)
npc <- predict(wisc.pr, newdata=new)
npc
plot(wisc.pr$x[,1:2], col = grps)
points(npc[,1], npc[,2], col = "blue", pch = 16)
```

