---
title: "class08"
author: "Xiao"
date: "2019/4/25"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## K-means clustering
```{r}
tmp <- c(rnorm(30,-3), rnorm(30,3))
x <- cbind(x=tmp, y=rev(tmp))
plot(x)
km <- kmeans(x, centers = 2, nstart = 20)
plot(x, col = km$cluster)
points(km$centers, pch = 18, col = "blue", cex = 3)
vcol <- c("blue","green")
#plotcluster(x, y$cluster, pch = y$cluster, clvecd=c(1,2), col=vcol[y$cluster])
```

## Hierarchical clustering example
We must give the *hclust()** function a distance matrix not the raw data as input
```{r}
# Distance matrix calculation
d <- dist(x)
#Clustering 
hc <- hclust(d)
plot(hc)
abline(h=6, col="red")
cutree(hc, h = 6) 
```

## Another Hierarchical clustering example but more real life with overlaping region
```{r}
x <- rbind(
 matrix(rnorm(100, mean=0, sd = 0.3), ncol = 2), # c1
 matrix(rnorm(100, mean = 1, sd = 0.3), ncol = 2), # c2
 matrix(c(rnorm(50, mean = 1, sd = 0.3), # c3
 rnorm(50, mean = 0, sd = 0.3)), ncol = 2))
colnames(x) <- c("x", "y")

plot(x)

col <- as.factor( rep(c("c1","c2","c3"), each=50) )
plot(x, col=col)
d <- dist(x)
hc <- hclust(d)
plot(hc)
gp2 <- cutree(hc, k = 2)
gp3 <- cutree(hc, k = 3)
#col <- as.factor(rep())
plot(x, col = gp3)
table(gp2, gp3)
```

## PCA
We will use the **prcomp()** function for PCA
```{r}
mydata <- read.csv("https://tinyurl.com/expression-CSV",
 row.names=1)
head(mydata, 10) 
nrow(mydata) # how many genes in my data
ncol(mydata) # how many cols in my data

# let do PCA
pca <- prcomp(t(mydata), scale = T)
attributes(pca)
plot(pca$x[, 1], pca$x[, 2], xlab = "PC1", ylab = "PC2")
## Precent variance is often more informative to look at
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1) 
head(pca.var.per)
## A vector of colors for wt and ko samples
colvec <- colnames(mydata)
colvec[grep("wt", colvec)] <- "red"
colvec[grep("ko", colvec)] <- "blue"
plot(pca$x[,1], pca$x[,2], col=colvec, pch=16,
 xlab=paste0("PC1 (", pca.var.per[1], "%)"),
 ylab=paste0("PC2 (", pca.var.per[2], "%)")) 
```

## UK PCA practice 
```{r}
# Q1
x <- read.csv("UK_foods.csv", row.names = 1)
dim(x)
head(x)

# Q2
barplot(as.matrix(x), beside = T, col = rainbow(nrow(x)))

# Q3
barplot(as.matrix(x), beside = F, col = rainbow(nrow(x)))

# Q5
pairs(x, col=rainbow(10), pch=16)

# Q6
```

## continue on previous section
```{r}
pca <- prcomp(t(x))
summary(pca)

#Plot PC1 vs PC2
plot(pca$x[, 1], pca$x[, 2], xlab = "PC1", ylab = "PC2", xlim=c(-270,500))
text(pca$x[, 1], pca$x[, 2], colnames(x))

v <- round( pca$sdev^2/sum(pca$sdev^2) * 100 )
v
```

